"""macOS menu-bar app for the CatanBot bridge (rumps).

A clickable toolbar item: start/stop the local bridge, a status dot, an
"open colonist.io and monitor" action, and a small settings menu. Run it
with `bin/catanbot-tray` (after `pip install -e '.[bridge,tray]'`).
bin/catanbot stays the canonical cross-platform launcher; this just
spawns the same bridge under the hood and offers one-click control.

rumps is a Cocoa wrapper that only installs on macOS, so the import is
guarded: the pip-installed `catanbot-tray` console script still imports
cleanly on Linux/Windows and exits with a clear message instead of an
ImportError.
"""
from __future__ import annotations

import json
import sys
import urllib.request
import webbrowser
from pathlib import Path

from catanbot.tray import process

try:
    import rumps
except ImportError:  # pragma: no cover - rumps is macOS-only
    rumps = None

# Menu-bar status icons, generated by bin/gen_tray_icons.py from the
# brand art and shipped with the package: full-color when running,
# desaturated and dim when stopped, two frames pulsed while starting.
_ASSETS = Path(__file__).resolve().parent / "assets"


def _icon(name: str) -> str | None:
    p = _ASSETS / f"tray_{name}.png"
    return str(p) if p.exists() else None


# Text fallback when the icon assets are missing (e.g. a non-editable
# install without package-data): show a status glyph rather than letting
# the menu-bar item go invisible (the title is otherwise empty).
_FALLBACK_TITLE = {
    "running": "🟢", "stopped": "⚪",
    "starting_a": "🟡", "starting_b": "🟡",
}


if rumps is not None:

    class CatanBotTray(rumps.App):
        def __init__(self) -> None:
            # Branded menu-bar icon. template=False so it shows in the
            # brand colors (not a monochrome silhouette); empty title so
            # the bar shows just the icon, like a typical status item.
            super().__init__("CatanBot", title="", quit_button=None)
            self.template = False
            self.port = process.DEFAULT_PORT
            self.menu = [
                "Start bridge",
                "Stop bridge",
                None,
                "Open colonist.io",
                None,
                ["Settings", ["Toggle Friendly Robber", "Set port…"]],
                None,
                "Quit CatanBot",
            ]
            self._cur_icon = None
            self._pulse_on = False
            self._pulse_frame = False
            # The 2s status poll drives the icon; a faster pulse timer
            # only runs while the bridge is starting, then stops so the
            # app sits idle (no steady CPU use).
            self._timer = rumps.Timer(self._refresh, 2)
            self._timer.start()
            self._pulse = rumps.Timer(self._tick_pulse, 0.45)
            self._set_icon("stopped")
            self._refresh(None)

        # --- status --------------------------------------------------
        def _set_icon(self, name: str) -> None:
            if name == self._cur_icon:
                return
            ico = _icon(name)
            if ico:
                self.icon = ico
                self.title = ""
            else:
                # Assets missing: keep a visible glyph so the item is
                # never blank.
                self.title = _FALLBACK_TITLE.get(name, "CatanBot")
            self._cur_icon = name

        def _refresh(self, _sender) -> None:
            st = process.status(self.port)
            if st == "starting":
                if not self._pulse_on:
                    self._pulse_on = True
                    self._pulse.start()
            else:
                if self._pulse_on:
                    self._pulse_on = False
                    self._pulse.stop()
                self._set_icon(st if st in ("running", "stopped")
                               else "stopped")

        def _tick_pulse(self, _sender) -> None:
            # Alternate the two starting frames for a subtle breathing
            # pulse while the bridge binds its port.
            self._pulse_frame = not self._pulse_frame
            self._set_icon("starting_b" if self._pulse_frame
                           else "starting_a")

        def _notify(self, msg: str) -> None:
            try:
                rumps.notification("CatanBot", "", msg)
            except Exception:  # noqa: BLE001
                pass

        # --- bridge control ------------------------------------------
        @rumps.clicked("Start bridge")
        def start(self, _sender) -> None:
            process.start(self.port)
            self._refresh(None)

        @rumps.clicked("Stop bridge")
        def stop(self, _sender) -> None:
            had_pid = process.read_pid() is not None
            process.stop()
            # A bridge started by hand (outside the app) has no pidfile,
            # so stop() can't reach it. Tell the user instead of leaving
            # the dot green with no feedback.
            if not had_pid and process.status(self.port) == "running":
                self._notify("Bridge was started outside the app; stop it "
                             "where you launched it")
            self._refresh(None)

        @rumps.clicked("Open colonist.io")
        def open_and_monitor(self, _sender) -> None:
            if process.status(self.port) == "stopped":
                process.start(self.port)
            webbrowser.open("https://colonist.io")
            self._refresh(None)

        # --- settings ------------------------------------------------
        @rumps.clicked("Settings", "Toggle Friendly Robber")
        def toggle_friendly_robber(self, sender) -> None:
            sender.state = 0 if sender.state else 1
            ok = self._post_config(
                {"friendly_robber_active": bool(sender.state)})
            self._notify(
                f"Friendly Robber {'on' if sender.state else 'off'}"
                if ok else "Start the bridge first to change settings")

        @rumps.clicked("Settings", "Set port…")
        def set_port(self, _sender) -> None:
            win = rumps.Window(
                title="Bridge port",
                message="Port the bridge listens on (default 8765):",
                default_text=str(self.port), dimensions=(120, 20))
            resp = win.run()
            if resp.clicked and resp.text.strip().isdigit():
                self.port = int(resp.text.strip())
                self._refresh(None)

        @rumps.clicked("Quit CatanBot")
        def quit_app(self, _sender) -> None:
            process.stop()
            rumps.quit_application()

        # --- helpers -------------------------------------------------
        def _post_config(self, body: dict) -> bool:
            url = f"http://{process.BRIDGE_HOST}:{self.port}/config"
            req = urllib.request.Request(
                url, data=json.dumps(body).encode("utf-8"), method="POST",
                headers={"Content-Type": "application/json"})
            try:
                with urllib.request.urlopen(req, timeout=1.0):
                    return True
            except Exception:  # noqa: BLE001
                return False

    def main() -> None:
        CatanBotTray().run()

else:

    def main() -> None:
        print(
            "catanbot-tray: the menu-bar app needs rumps, which installs on "
            "macOS only.\n"
            "  macOS:          pip install -e '.[tray]'  then  "
            "./bin/catanbot-tray\n"
            "  Linux/Windows:  run the bridge with  ./bin/catanbot live",
            file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
