"""macOS menu-bar app for the CatanBot bridge (rumps).

A clickable toolbar item: start/stop the local bridge, a status dot, an
"open colonist.io and monitor" action, and a small settings menu. Run it
with `bin/catanbot-tray` (after `pip install -e '.[bridge,tray]'`).
bin/catanbot stays the canonical cross-platform launcher; this just
spawns the same bridge under the hood and offers one-click control.

rumps is a Cocoa wrapper that only installs on macOS, so the import is
guarded: the pip-installed `catanbot-tray` console script still imports
cleanly on Linux/Windows and exits with a clear message instead of an
ImportError.
"""
from __future__ import annotations

import json
import sys
import threading
import urllib.request
import webbrowser
from pathlib import Path

from catanbot.tray import process

try:
    import rumps
    from PyObjCTools import AppHelper
except ImportError:  # pragma: no cover - rumps is macOS-only
    rumps = None
    AppHelper = None

# Menu-bar status icons, generated by bin/gen_tray_icons.py from the
# brand art and shipped with the package: full-color when running,
# desaturated and dim when stopped, two frames pulsed while starting.
_ASSETS = Path(__file__).resolve().parent / "assets"


def _icon(name: str) -> str | None:
    p = _ASSETS / f"tray_{name}.png"
    return str(p) if p.exists() else None


# Text fallback when the icon assets are missing (e.g. a non-editable
# install without package-data): show a status glyph rather than letting
# the menu-bar item go invisible (the title is otherwise empty).
_FALLBACK_TITLE = {
    "running": "🟢", "stopped": "⚪",
    "starting_a": "🟡", "starting_b": "🟡",
    "golive_1": "🟢", "golive_2": "🟢", "golive_3": "🟢",
}


if rumps is not None:

    class CatanBotTray(rumps.App):
        def __init__(self) -> None:
            # Branded menu-bar icon. template=False so it shows in the
            # brand colors (not a monochrome silhouette); empty title so
            # the bar shows just the icon, like a typical status item.
            super().__init__("CatanBot", title="", quit_button=None)
            self.template = False
            self.port = process.DEFAULT_PORT
            self.menu = [
                "Start bridge",
                "Stop bridge",
                None,
                "Open colonist.io",
                None,
                ["Settings", ["Toggle Friendly Robber", "Set port…"]],
                None,
                "Quit CatanBot",
            ]
            self._cur_icon = None
            self._pulse_on = False
            self._pulse_frame = False
            self._glow_on = False
            self._glow_step = 0
            # Serializes start/stop so a click and the background poll can
            # never double-spawn; _probing is single-flight for the poll.
            self._lock = threading.Lock()
            self._probing = False
            # The 2s poll drives the icon, but the actual socket/ps probe
            # runs on a worker thread (see _refresh) so the menu never
            # blocks. The faster pulse + one-shot go-live glow timers only
            # run during their animation, then stop, so the app sits idle.
            self._timer = rumps.Timer(self._refresh, 2)
            self._timer.start()
            self._pulse = rumps.Timer(self._tick_pulse, 0.45)
            self._glow = rumps.Timer(self._tick_glow, 0.18)
            # Optimistic: the app auto-starts the bridge, so show the
            # 'starting' pulse immediately, then bring the bridge up off
            # the main thread and reconcile. start() adopts a bridge already
            # on the port instead of spawning a duplicate, so a relaunch is
            # harmless. Clicking the app should get you a running advisor,
            # not a dot you then have to click "Start bridge" on.
            self._render("starting")
            threading.Thread(target=self._start_worker, daemon=True).start()

        # --- icon rendering (main thread only) -----------------------
        def _set_icon(self, name: str) -> None:
            if name == self._cur_icon:
                return
            ico = _icon(name)
            if ico:
                self.icon = ico
                self.title = ""
            else:
                # Assets missing: keep a visible glyph so the item is
                # never blank.
                self.title = _FALLBACK_TITLE.get(name, "CatanBot")
            self._cur_icon = name

        def _render(self, st: str) -> None:
            """Drive the menu-bar icon for a status string. MUST run on the
            main thread (called from timers, click handlers, and AppHelper
            callbacks marshalled back from the probe worker)."""
            if st == "starting":
                self._cancel_glow()
                if not self._pulse_on:
                    self._pulse_on = True
                    self._pulse.start()
                return
            if self._pulse_on:
                self._pulse_on = False
                self._pulse.stop()
            if st == "running":
                if self._glow_on:
                    return  # the glow animation owns the icon until it settles
                if self._cur_icon != "running":
                    self._start_glow()   # one-shot bloom on go-live
                else:
                    self._set_icon("running")
                return
            # stopped (or any unexpected value)
            self._cancel_glow()
            self._set_icon("stopped")

        def _tick_pulse(self, _sender) -> None:
            # Alternate the two starting frames for a subtle breathing
            # pulse while the bridge binds its port.
            self._pulse_frame = not self._pulse_frame
            self._set_icon("starting_b" if self._pulse_frame
                           else "starting_a")

        def _start_glow(self) -> None:
            self._glow_on = True
            self._glow_step = 0
            self._glow.start()

        def _tick_glow(self, _sender) -> None:
            # One-shot bloom: ramp the glow up then settle to steady green,
            # then stop the timer so the app returns to zero idle CPU.
            frames = ("golive_1", "golive_2", "golive_3")
            if self._glow_step < len(frames):
                self._set_icon(frames[self._glow_step])
                self._glow_step += 1
            else:
                self._cancel_glow()
                self._set_icon("running")

        def _cancel_glow(self) -> None:
            if self._glow_on:
                self._glow.stop()
                self._glow_on = False

        # --- status polling (off the main thread) --------------------
        def _refresh(self, _sender=None) -> None:
            # Called on the main thread (2s timer / reconcile). Kick a
            # single background probe; never block the UI on socket/ps.
            if self._probing:
                return
            self._probing = True
            threading.Thread(target=self._probe_worker, daemon=True).start()

        def _probe_worker(self) -> None:
            try:
                st = process.status(self.port)
            except Exception:  # noqa: BLE001
                st = "stopped"
            AppHelper.callAfter(self._apply_status, st)

        def _apply_status(self, st: str) -> None:
            self._probing = False
            self._render(st)

        def _notify(self, msg: str) -> None:
            try:
                rumps.notification("CatanBot", "", msg)
            except Exception:  # noqa: BLE001
                pass

        # --- bridge control ------------------------------------------
        def _start_worker(self) -> None:
            with self._lock:
                try:
                    process.start(self.port)
                except Exception:  # noqa: BLE001
                    pass
            AppHelper.callAfter(self._refresh, None)

        def _stop_worker(self) -> None:
            with self._lock:
                try:
                    signaled = process.stop(port=self.port)
                except Exception:  # noqa: BLE001
                    signaled = False
            if not signaled:
                AppHelper.callAfter(self._notify,
                                    "No bridge was running to stop")
            AppHelper.callAfter(self._refresh, None)

        @rumps.clicked("Start bridge")
        def start(self, _sender=None) -> None:
            # Instant feedback before any blocking work.
            self._render("starting")
            threading.Thread(target=self._start_worker, daemon=True).start()

        @rumps.clicked("Stop bridge")
        def stop(self, _sender=None) -> None:
            # Instant feedback; the real stop (incl. an externally-started
            # bridge, resolved by port) runs off the main thread.
            self._render("stopped")
            threading.Thread(target=self._stop_worker, daemon=True).start()

        @rumps.clicked("Open colonist.io")
        def open_and_monitor(self, _sender=None) -> None:
            webbrowser.open("https://colonist.io")
            self._render("starting")
            threading.Thread(target=self._start_worker, daemon=True).start()

        # --- settings ------------------------------------------------
        @rumps.clicked("Settings", "Toggle Friendly Robber")
        def toggle_friendly_robber(self, sender) -> None:
            sender.state = 0 if sender.state else 1
            ok = self._post_config(
                {"friendly_robber_active": bool(sender.state)})
            self._notify(
                f"Friendly Robber {'on' if sender.state else 'off'}"
                if ok else "Start the bridge first to change settings")

        @rumps.clicked("Settings", "Set port…")
        def set_port(self, _sender) -> None:
            win = rumps.Window(
                title="Bridge port",
                message="Port the bridge listens on (default 8765):",
                default_text=str(self.port), dimensions=(120, 20))
            resp = win.run()
            if resp.clicked and resp.text.strip().isdigit():
                self.port = int(resp.text.strip())
                self._refresh(None)

        @rumps.clicked("Quit CatanBot")
        def quit_app(self, _sender=None) -> None:
            # Synchronous on quit: make sure the bridge is actually gone
            # before the app exits (a few seconds is fine here).
            process.stop(port=self.port)
            rumps.quit_application()

        # --- helpers -------------------------------------------------
        def _post_config(self, body: dict) -> bool:
            url = f"http://{process.BRIDGE_HOST}:{self.port}/config"
            req = urllib.request.Request(
                url, data=json.dumps(body).encode("utf-8"), method="POST",
                headers={"Content-Type": "application/json"})
            try:
                with urllib.request.urlopen(req, timeout=1.0):
                    return True
            except Exception:  # noqa: BLE001
                return False

    def main() -> None:
        CatanBotTray().run()

else:

    def main() -> None:
        print(
            "catanbot-tray: the menu-bar app needs rumps, which installs on "
            "macOS only.\n"
            "  macOS:          pip install -e '.[tray]'  then  "
            "./bin/catanbot-tray\n"
            "  Linux/Windows:  run the bridge with  ./bin/catanbot live",
            file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
